INSERT INTO project_location_provinces (country_code, country_name, province_code, province_name)
VALUES
  ('USA', 'USA', 'AL', 'Alabama'),
  ('USA', 'USA', 'AK', 'Alaska'),
  ('USA', 'USA', 'AZ', 'Arizona'),
  ('USA', 'USA', 'AR', 'Arkansas'),
  ('USA', 'USA', 'CA', 'California'),
  ('USA', 'USA', 'CO', 'Colorado'),
  ('USA', 'USA', 'CT', 'Connecticut'),
  ('USA', 'USA', 'DE', 'Delaware'),
  ('USA', 'USA', 'FL', 'Florida'),
  ('USA', 'USA', 'GA', 'Georgia'),
  ('USA', 'USA', 'HI', 'Hawaii'),
  ('USA', 'USA', 'ID', 'Idaho'),
  ('USA', 'USA', 'IL', 'Illinois'),
  ('USA', 'USA', 'IN', 'Indiana'),
  ('USA', 'USA', 'IA', 'Iowa'),
  ('USA', 'USA', 'KS', 'Kansas'),
  ('USA', 'USA', 'KY', 'Kentucky'),
  ('USA', 'USA', 'LA', 'Louisiana'),
  ('USA', 'USA', 'ME', 'Maine'),
  ('USA', 'USA', 'MD', 'Maryland'),
  ('USA', 'USA', 'MA', 'Massachusetts'),
  ('USA', 'USA', 'MI', 'Michigan'),
  ('USA', 'USA', 'MN', 'Minnesota'),
  ('USA', 'USA', 'MS', 'Mississippi'),
  ('USA', 'USA', 'MO', 'Missouri'),
  ('USA', 'USA', 'MT', 'Montana'),
  ('USA', 'USA', 'NE', 'Nebraska'),
  ('USA', 'USA', 'NV', 'Nevada'),
  ('USA', 'USA', 'NH', 'New Hampshire'),
  ('USA', 'USA', 'NJ', 'New Jersey'),
  ('USA', 'USA', 'NM', 'New Mexico'),
  ('USA', 'USA', 'NY', 'New York'),
  ('USA', 'USA', 'NC', 'North Carolina'),
  ('USA', 'USA', 'ND', 'North Dakota'),
  ('USA', 'USA', 'OH', 'Ohio'),
  ('USA', 'USA', 'OK', 'Oklahoma'),
  ('USA', 'USA', 'OR', 'Oregon'),
  ('USA', 'USA', 'PA', 'Pennsylvania'),
  ('USA', 'USA', 'RI', 'Rhode Island'),
  ('USA', 'USA', 'SC', 'South Carolina'),
  ('USA', 'USA', 'SD', 'South Dakota'),
  ('USA', 'USA', 'TN', 'Tennessee'),
  ('USA', 'USA', 'TX', 'Texas'),
  ('USA', 'USA', 'UT', 'Utah'),
  ('USA', 'USA', 'VT', 'Vermont'),
  ('USA', 'USA', 'VA', 'Virginia'),
  ('USA', 'USA', 'WA', 'Washington'),
  ('USA', 'USA', 'WV', 'West Virginia'),
  ('USA', 'USA', 'WI', 'Wisconsin'),
  ('USA', 'USA', 'WY', 'Wyoming'),
  ('USA', 'USA', 'DC', 'District of Columbia'),
  ('CAN', 'Canada', 'AB', 'Alberta'),
  ('CAN', 'Canada', 'BC', 'British Columbia'),
  ('CAN', 'Canada', 'MB', 'Manitoba'),
  ('CAN', 'Canada', 'NB', 'New Brunswick'),
  ('CAN', 'Canada', 'NL', 'Newfoundland and Labrador'),
  ('CAN', 'Canada', 'NS', 'Nova Scotia'),
  ('CAN', 'Canada', 'ON', 'Ontario'),
  ('CAN', 'Canada', 'PE', 'Prince Edward Island'),
  ('CAN', 'Canada', 'QC', 'Quebec'),
  ('CAN', 'Canada', 'SK', 'Saskatchewan'),
  ('CAN', 'Canada', 'NT', 'Northwest Territories'),
  ('CAN', 'Canada', 'NU', 'Nunavut'),
  ('CAN', 'Canada', 'YT', 'Yukon')
ON CONFLICT (country_code, province_code) DO UPDATE
SET
  country_name = EXCLUDED.country_name,
  province_name = EXCLUDED.province_name;
